# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#hello:
#    pattern:  /hello/{name}
#    defaults: { _controller: AcmeHelloBundle:Hello:index }

AcmeHelloBundle:
    resource: "@AcmeHelloBundle/Controller"
    type: annotation