# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#hello:
#    pattern:  /hello/{name}
#    defaults: { _controller: AcmeHelloBundle:Hello:index }

#AcmeHelloBundle:
#    resource: "@AcmeHelloBundle/Controller"
#    type: annotation

hello2:
    pattern:  /hello2/{name}
    defaults: { _controller: AcmeHelloBundle:Hello2:index }

hello3:
    pattern:  /hello3/{name}
    defaults: { _controller: AcmeHelloBundle:Hello3:index }