services:

  controller.form_test2:
    class: Acme\HelloBundle\Controller\FormTest2Controller

  controller.hello2:
    class: Acme\HelloBundle\Controller\Hello2Controller

  facade.fetch_products_facade:
    class: Acme\HelloBundle\Facade\FetchProductsFacade

  facade.insert_test_entity_facade:
    class: Acme\HelloBundle\Facade\InsertTestEntityFacade
    arguments: [@doctrine.orm.default_entity_manager]

  form.testPostForm:
    class: Acme\HelloBundle\Form\TestPostForm

  pokus2:
    class: Collabim\Pokus2

  pokus:
    class: Collabim\Pokus
    arguments: [%myTestOption%]

  repository.products_repository:
    class: Acme\HelloBundle\Repository\ProductsRepository
    arguments: [@doctrine.orm.default_entity_manager]
